### ISSUE TITLE
investigate: why KSP stops responding to OS events while loading akrOS

### ISSUE THREAD

**Issue by abenkovskii** [akrasuski1/akrOS#26]

**Comment by akrasuski1** [comment]
I guess it is kOS trying to compile the whole thing in one frame. But this is just a guess. Maybe we should try compiling it first and run it from .ksm to see if it fixes the problem.

**Comment by akrasuski1** [comment]
Yep, I think I confirmed my guess - adding `wait 0.001.` between `run` statements makes kOS give KSP one frame of time. I don't know if we should add those `wait`s? It is technically a redundant slowing of akrOS. I'd say we should wait for kOS developers to:

> eventually use another thread for it

What do you think?

**Comment by abenkovskii** [comment]
Have you tried compiling akrOS before running? It might help.

**Comment by akrasuski1** [comment]
I haven't yet - being busy with process manager and stuff. But that's something worth trying.

**Comment by abenkovskii** [comment]
> I don't know if we should add those waits?

It isn't the first time you have to use a workaround for a KSP ar kOS bug. Is it? Besides I don't think it's much of slowdown.

**Comment by akrasuski1** [comment]
Yeah, the additional one secod total of wait is probably okay. But the game would still freeze. Without waits, it was one, 5-second long freeze, and with them, it's 5 one-second long freezes. For me, it doesn't matter that much, as the game is unplayable either way. Technically, we could split the files so that every (EVERY) function is in separate file and then put `wait`s after each function. But that would cause chaos and I'd like to avoid it.

**Comment by abenkovskii** [comment]
I'll check out this: https://github.com/KSP-KOS/KOS/pull/976 and try to run a compiled akrOS.

**Comment by abenkovskii** [comment]
It does speed the loading up. AkrOS loads a lot faster if compiled beforehand.

**Comment by akrasuski1** [comment]
That's great. I wonder if there is any way to compile a file to .ksm automatically if and only if the source has been modified after binary has been modified... The kOS docs mention :modified file suffix, but I couldn't get it to work. I guess that will have to wait until later.

**Comment by abenkovskii** [comment]
What exactly happens when you try using `:modified`? It may be related to this issue: https://github.com/KSP-KOS/KOS/issues/757.

**Comment by abenkovskii** [comment]
BTW. The "investigation" is complete. I'm closing the issue.
