### ISSUE TITLE
Is it possible to display the tooltip about switching windows constantly?

### ISSUE THREAD

**Issue by abenkovskii** [akrasuski1/akrOS#28]

**Comment by akrasuski1** [comment]
What, where and when? Please be more specific.

**Comment by abenkovskii** [comment]
In the tooltip. In case the user forgets it.

**Comment by akrasuski1** [comment]
Oh, you mean the status bar (the bottom, screen-wided window)? I don't  really want to make the status any wider (_maybe_ one more line could be squeezed, but that's it). But I wanted the status to be playground for widgets. 

Right now, the most probable place where a new user would be stuck at, is the main menu - if he doesn't know how to switch windows, it's unlikely he switches them by accident. And the tip is there.

**Comment by abenkovskii** [comment]
> the tip is there.

currently this tip is in the loading screen

**Comment by akrasuski1** [comment]
Solution idea: https://github.com/akrasuski1/akrOS/issues/30

**Comment by akrasuski1** [comment]
![image](https://cloud.githubusercontent.com/assets/5507813/7445976/56876102-f1c8-11e4-8057-654cbe4d63d2.png)
That's how it looks. I tried to minimize the place it takes, given that it stays at the screen at all times.

**Comment by abenkovskii** [comment]
:+1:

**Comment by akrasuski1** [comment]
Oh, and just to have common vocabulary:
The "status window" is the rectangle on the bottom _left_.
The "tip" is the rectangle on the bottom _right_.
The "status bar" or just "status" is a fuzzy term and can sometimes mean the whole rectangle at the bottom (status window + tip) or just the status window.

**Comment by abenkovskii** [comment]
Thanks
