### ISSUE TITLE
Showing start dialog only once

### ISSUE THREAD

**Issue by abenkovskii** [akrasuski1/akrOS#30]
I don't like to press 9 every time I want to access the main menu.

**Comment by akrasuski1** [comment]
That's a fair concern. Where would you put general info (ag1 and ag2 to flip selection) though? Right now it is in status bar of that screen.

**Comment by abenkovskii** [comment]
I think we need to somehow fit the information about ag1 and ag2 into the main menu tooltip or even display this information constantly.

**Comment by akrasuski1** [comment]
Actually, we can split the status bar into two parts, like this:

```
+========================================+=====+
|         widget stuff                   | 1/2 |
+========================================+=====+
```

with the right part containing the very short note about the ag1 and ag2 and the left part being left over for apps.

**Comment by akrasuski1** [comment]
You can still go to the title screen if you press `Back` at the main menu.
