### ISSUE TITLE
1 and 2 are working in the window manager (but should not)

### ISSUE THREAD

**Issue by abenkovskii** [akrasuski1/akrOS#35]
![screenshot0](https://cloud.githubusercontent.com/assets/11031560/7447383/3d40d2ac-f202-11e4-8d31-4b3e204bc82e.png)

**Comment by abenkovskii** [comment]
Notice the state of status window: the window 2 is selected and receiving input.

**Comment by akrasuski1** [comment]
Nice screenshot :) Seems that the debug `FOCUS` field is useful after all.
