### ISSUE TITLE
It's possible to open more than one process in the same window

### ISSUE THREAD

**Issue by abenkovskii** [akrasuski1/akrOS#38]
![screenshot0](https://cloud.githubusercontent.com/assets/11031560/7447433/72591ca4-f204-11e4-880a-efef5800bb8e.png)
Notice: window 2 has overlapping vessel stats and process manager.

**Comment by abenkovskii** [comment]
This happens when opening window manager while having processes "sharing" window:
![screenshot2](https://cloud.githubusercontent.com/assets/11031560/7447467/5bff3ef6-f205-11e4-8e96-7ead36bf3a3f.png)

**Comment by akrasuski1** [comment]
Those are separate issues. Please post one of them in separate issue (preferably the second one - it is caused probably by job_menu trying to draw while it is in background)

**Comment by abenkovskii** [comment]
I thought that the 2-nd bug is caused by the 1-st. Turns out I was wrong.

**Comment by akrasuski1** [comment]
Yeah, that was my first impression as well. But the second bug is reproduced by having process manager in second window and running window manager.

**Comment by akrasuski1** [comment]
What should happen when you in process manager switch window to already taken one? Just nothing? Note to self: same applies to running from main menu.

**Comment by akrasuski1** [comment]
Proposed solution: when running processs manager or main menu, list only those windows that are still free (and background).
