### ISSUE TITLE
Rename draw_outline.

### ISSUE THREAD

**Issue by akrasuski1** [akrasuski1/akrOS#4]
I think we can split it into two functions: draw_filled_window(wnd,char), which may draw such a window:

```
+==+
|..|
+==+
```

if given dot as a second character. The second, much more frequently used version, would be draw_empty_window, which calls the first version with space as argument.

**Comment by abenkovskii** [comment]
or we can take an argument `background_character`

**Comment by akrasuski1** [comment]
yep, that's what I meant in the first version. But since in vast amount of cases we use space, I think it's worth a separate function (draw_empty_window)

**Comment by akrasuski1** [comment]
Done.
