### ISSUE TITLE
Opening window manager while having process manager open causes crash

### ISSUE THREAD

**Issue by abenkovskii** [akrasuski1/akrOS#41]
![screenshot2](https://cloud.githubusercontent.com/assets/11031560/7447515/fcb747c0-f206-11e4-9a25-f442eaa701a7.png)

**Comment by akrasuski1** [comment]
Fixed. In the future, we should remember to surround any `get_process_window` calls with `if is_process_gui` checks. Otherwise, the program crashes when it's backgrounded.
