### ISSUE TITLE
Some files in akrOS rely on some other files to be imported by other parts of OS

### ISSUE THREAD

**Issue by abenkovskii** [akrasuski1/akrOS#45]
I think it's better to explicitly import everything you are using in each file. Example: job_vessel_stats should contain the line `run lib_os_data.` because it uses it's function `get_status_window`. Without explicit imports it's impossible to find where a certain function is declared. Besides the current approach makes it possible to break one file while editing another seemingly unrelated to it.

**Comment by akrasuski1** [comment]
I haven't made performance tests, but I think that those redundant `run`s would make the start even slower. Either way, I guess we should import those common files in the main file - the system won't even start without them anyway. The other `job`s should include their custom libraries on their own, though.

**Comment by abenkovskii** [comment]
It's probably not too much of a slowdown because:
1. at a standard temperature and pressure the compilation of each file occurs only once and
2. the "body" of a file that just declares a bunch of functions is usually pretty small (like a dozen of opcodes).
P.S. I didn't do performance tests too

**Comment by abenkovskii** [comment]
P.P.S. If you want to take a look behind the scenes of kOS:
1. Write a simple script
2. Add a line `print 1/0.` to it
3. Run it
4. Open <your_ksp_path>/KSP_Data/output_log.txt and scroll all the way down
5. You will see the bytecode your program was compiled to

**Comment by akrasuski1** [comment]
Yeah, the performance argument is weak, especially with your testing that compiled version is much faster. But I still think that the common/system functions don't need to be included in every widget file, as those particular functions can be safely assumed to be provided with system environment itself.
