### ISSUE TITLE
Problem with main menu child

### ISSUE THREAD

**Issue by abenkovskii** [akrasuski1/akrOS#47]
1. It displays as "main menu" in the process manager
2. The process can't be moved to main menu window, only created there. It's confusing.
   Proposal: because we can now close or hide main menu without any problems we can disable an option "This Window".

**Comment by akrasuski1** [comment]
ok, this is a problem. But with your solution we would have no way to draw on all three windows (with main menu hidden or closed).
Proposed solution: 
Still have "This window" option there, but make it close main window automatically, and not run it as child. Is it ok?

**Comment by abenkovskii** [comment]
Yes that's better.
