### ISSUE TITLE
[bug] Strange window manager behaviour

### ISSUE THREAD

**Issue by abenkovskii** [akrasuski1/akrOS#49]
When opened from main menu not in window 0 it moves focus to window 0:
![screenshot11](https://cloud.githubusercontent.com/assets/11031560/7554945/3e7fd4ba-f743-11e4-9c01-e56f18982b2b.png)
- produces many fun pictures.

**Comment by akrasuski1** [comment]
I think it is fixed. But it was painful, so it's better you confirm it.

**Comment by abenkovskii** [comment]
I can't test it because of this: #50.

**Comment by abenkovskii** [comment]
Looks like you fixed it.
