### ISSUE TITLE
No controls and empty status window in window manager

### ISSUE THREAD

**Issue by abenkovskii** [akrasuski1/akrOS#50]
![screenshot14](https://cloud.githubusercontent.com/assets/11031560/7556271/71faab74-f772-11e4-9b28-6aec77113902.png)

**Comment by akrasuski1** [comment]
Strange, it works for me. Are you simply choosing Window Manager from main menu, and that's it? Or are there more complicated steps to reproduce?

~~I will double check if I uploaded correct version of files to GitHub, but I think they're ok.~~

EDIT: Turns out I didn't. Sorry for wasting time...

**Comment by abenkovskii** [comment]
> Or are there more complicated steps to reproduce?

Compiling could affect it. But I'm sure I was testing it on the version with dunbaratu's fix

**Comment by akrasuski1** [comment]
I uploaded version I initially intended to. This one has window manager working (at least I think so)

**Comment by abenkovskii** [comment]
I'll test it tomorrow. Going to bed now.

**Comment by akrasuski1** [comment]
Sure. Good night! :zzz:

**Comment by akrasuski1** [comment]
Any update on this?

**Comment by abenkovskii** [comment]
Looks like you fixed it.
