### ISSUE TITLE
Implement process manager.

### ISSUE THREAD

**Issue by akrasuski1** [akrasuski1/akrOS#6]
It should be a widget. Initially it shows an ordinary menu (as child process), with options:
1. Kill process.
2. Change process window.
3. Show processes.
4. Quit.
Whenever any option other than quit is selected, it changes child processs into another menu with list of processes (and maybe back button?). Upon selection, selected action is applied to that process - in case of window change, there is also another menu with actual window selection.

**Comment by abenkovskii** [comment]
- There should definitely be a cancel button and may be a confirmation dialog too.
- My instinct is to flip it other way round: select a process first, then action.
- What does "show processes" does?

**Comment by akrasuski1** [comment]
Yep, if we show processes first, we can skip "show processes", as it will be redundant. I'd do quit button at process list and Cancel button at action list.
