### ISSUE TITLE
Implement window manager.

### ISSUE THREAD

**Issue by akrasuski1** [akrasuski1/akrOS#7]
This is a bit hard to do. My proposition is that we don't do it as a widget, because it's very close to the OS layer, and as such, it should be ran as child process of main menu.

> Yeah, I thought of a simple interface like that:
> AG0 - accept current window and go to next one.
> AG9 - cycle vertical split, horizontal split, no split at all at current window.
> AG7/8 - decrease/increase split ratio of the current window.
> When window is accepted, if it was split, the new window go to the end of the to-do queue, otherwise, the window is accepted and no longer needs thought. When no more windows are in queue, accept new window configuration.
> The currently editted window would be somehow marked as selected, I don't know how though yet. Perhaps the background of that window should be made of dots (".") instead of spaces?
## 

> I think that at the exact moment you click "window manager" option from program selection, the whole screen should turn into one window covering whole terminal. Inside this window there are instructions for window manager (and note on the bottom, saying: ag9 to start. Also ag1 should be able to abort window selection at any time and revert to old configuration). After clicking continue, I don't think any instructions should stay on screen (instructions should warn about that). And then window selection process starts. When you're done (provided you didn't abort), the main menu should show on window 0, and any processes that had previously been on windows that are curently still visible, should be still visible. Those, which had too big window index, go to background (e.g. you had windows 0,1,2, each of which had a process running, then you resize to just two windows, so only 0,1 stay. Process in window 2 goes to background and is reachable only via process manager).

**Comment by abenkovskii** [comment]
We can add a status bar at the bottom of the screen always (not only in the window manager mode) showing current controls. If we exclude it from being managed by the window manager we will be able to display it's controls too.

**Comment by akrasuski1** [comment]
Hmmm. That might work. I'd just make the place for windows terminal:height-5 or so, and the rest to be reserved for controls.

**Comment by akrasuski1** [comment]
Right now I've added a backbone of the window management system - functions to recursively draw divided windows to screen (btw, got idea for better function name than os_draw_divided_window?)
Does it look sensible?

**Comment by akrasuski1** [comment]
Now, after a bit of hard work (recursive DFS on kOS lists is not my dream), I have a first version of window manager working. The controls, for now, are printed on the window number 0. Eventually, they will be printed at the bottom of the screen, as you suggested.
What do you think of the interface? I know the windows take a bit to update, but it's not that bad IMO. I'll still have to somehow denote selected window - it's not that easy though. For now, you may orient yourself by clicking ag9 to see where you are.

**Comment by akrasuski1** [comment]
Done
