### ISSUE TITLE
New widget - hibernate as.

### ISSUE THREAD

**Issue by akrasuski1** [akrasuski1/akrOS#8]
It would save current OS state so that it can be restored later.

**Comment by abenkovskii** [comment]
I think it should wait until we have RTTI. With it we can write a generic serialization/deserialization for KSLib. Without It we can't properly handle cases where widget has list fields.

**Comment by akrasuski1** [comment]
Yep, I haven't put much thought into it yet. I just put it there to remember about it later.

**Comment by akrasuski1** [comment]
Closing this as a duplicate of #9
